### ISSUE TITLE
correct_pH for complex

### ISSUE THREAD

**Issue by velocirraptor23** [CCPBioSim/fesetup#15]
Hi, I have noticed that when running FESetup, in the part of complexation it brings the protein.pdb to the folder instead of the protonated.pdb. If this is true then pH is not correct. What is pH by default? Is there any way to take the protonated option?

**Comment by ppxasjsm** [comment]
I think it should be possible to specify which pdb file to use for complexation. For example you can just run complexation on its own.

If you give details of your input config file it might be easier to track what is going on. I have no idea what exactly you are doing. 

It might also be worthwhile considering to migrate to using [BioSimSpace](https://biosimspace.org) for the setup rather than FESetup.

**Comment by velocirraptor23** [comment]
BioSImSpace sounds awesome, I just tried it but I'm gonna make some tests. What I'm doing is inputs preparation for SIRE. I wanted to get inputs ready at pH = 7.3 and I added propka term. I got protonated.pdb, however when the complex was made FESetup took protein.pdb again and the solvated system was made with the original pdb. Then I realized that to take correct protonation I should change protonated.pdb to protein.pdb before to run complexation separately.

**Comment by velocirraptor23** [comment]
I think it needs to also specify pH during minimization, but before we need to change aminoacids names to specify which ones are implied on this (achieved with PROPKA). Not sure if we need to keep also pH during simulation running in SIRE.

**Comment by ppxasjsm** [comment]
You can use the protonated.pdb as input with BioSimSpace and then just carry on running your simulation protocol. That should work fine.

**Comment by velocirraptor23** [comment]
Ok. great. Ill do that. 

Bests

Cesar
